# Netscape HTTP Cookie File
# http://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_aur.archlinux.org	FALSE	/	TRUE	1366640587	AURSID	3be02d0b98a9703346f1ac481e4652f1
aur.archlinux.org	FALSE	/	FALSE	1366640588	AURLANG	en
